agent_name = "ginger"
#image = "pierretokns/ginger:latest"
image = "natea/ginger:latest"
secret_set = "ginger-secrets"
agent_profile = "agent-1x"

# RECOMMENDED: Set an image pull secret:
# https://docs.pipecat.ai/deployment/pipecat-cloud/fundamentals/secrets#image-pull-secrets
#image_credentials = "your_image_pull_secret"

[scaling]
	min_agents = 1
